[package]
name = "photo2cull"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
eframe = "0.36.2"
egui = "0.36.2"
image = { version = "0.25.10", features = ["rayon"] }
imagepipe = "0.5.1"
imageproc = "0.27.0"
rawloader = "0.37.2"
rayon = "1.12.0"
rfd = "0.17.2"
serde = "1.0.229"
walkdir = "2.5.0"
